### ISSUE TITLE
local files vs. shared files

### ISSUE THREAD

**Issue by ohspite** [tarsius/no-littering#20]
Some of the paths that this package will manage are things that most users wouldn't want to sync between computers; for example, `recentf-save-file` or `trash-directory`.  (I mean that users probably wouldn't want to sync the actual *files* in those paths, even though the locations of the files could be the same on all computers.)  But there are other files, like `abbrev-file-name`, that most users would want to sync between computers.  

Would it complicate things too much to have something like `var`, `etc`, `var-local`, and `etc-local`?  Then users could just sync `var` and `etc`. 

If this seems like an issue to address, then another issue is that there are some files (`shared-game-score-directory` maybe?) that some users would want to sync and others wouldn't.  Maybe it makes sense to just create sane defaults and let the user deal with it if they want to override them.  On the other hand, an interface could be provided that lets the user easily override the `no-littering` path for certain files.

**Comment by tarsius** [comment]
I think whether a file should by synced or not is orthogonal to the question where it should be saved.

Instead of placing the files that are not to be synced in a different location, you could tell the tool which does the syncing to exclude those files. If you used git, then you would do that using `.gitignore`. If you use something like dropbox, then I would hope that that also has some exclusion mechanism (if not, then that is a strong argument in favor of using something else).

**Comment by ohspite** [comment]
I definitely see the perspective.  Using `.gitignore` is what I'm doing now.  On the other hand, the idea with `no-littering` is for users to magically not have to configure stuff for where packages write random files every time they install a new package.  It would be kind of nice if you could just add `var/local` and `etc/local` (or whatever) to `.gitignore` one time, and then be done with it.

**Comment by tarsius** [comment]
Or maybe we could just provide an example `.gitignore` in the documentation.

**Comment by ohspite** [comment]
I think you're right--handling it with an ignore list on the git side of things does seem like a good way of doing it.  One option is to actually write an example `gitignore` file (called something other than `.gitignore`) in the `no-littering-etc`/`-var` directories and keep the example file up to date when new packages are "themed".  Then, if the user wants, they could symlink `.gitignore` to that file and have it kept up to date for them.  

Thank you, by the way, for starting this package.  This problem has annoyed me for over ten years.

**Comment by tarsius** [comment]
I don't really want to add example `.gitignore` files. If we did that, then that would increase the work of contributors because they would have to decide whether they and other users would want to synchronize that file or not. And if they didn't do it, then I would have to do it, actually even if they did I would want to make sure that I agree.

Also some user might want to synchronize a certain file, while an other might not. I think we should just add an example `.gitignore` to the wiki. I've setup that page here: https://github.com/tarsius/no-littering/wiki/How-to-synchronize-only-some-files-between-machines. Maybe you could provide the initial example `.gitignore`. Thanks!
