### ISSUE TITLE
What about package-user-dir?

### ISSUE THREAD

**Issue by DamienCassou** [tarsius/no-littering#35]
Is it normal that this variable is not themed? Do you want a PR?

**Comment by tarsius** [comment]
> Is it normal that this variable is not themed?

Most variables that could be themed, aren't. So yes, that's normal.

> Do you want a PR?

No. In this case it is intentional that this isn't themed. It doesn't belong in `var` or `etc` -- it is equivalent to `lib`. (Personally I don't use `package.el` but my `borg.el`, which actually installs into `lib`, but I see no reason to change the name of `package.el`'s respective directory.)

**Comment by DamienCassou** [comment]
I think the no-littering documentation is a bit lacking regarding what should land in `var` vs. `etc` (and `lib`).

**Comment by tarsius** [comment]
Well... any suggestions on how to improve it, aka patches welcome :-)

(I thought the names of these directories are a strong enough hint on what belongs there, think `/etc` and `/var`.)

**Comment by justbur** [comment]
`package-user-dir` should definitely not be themed by default. This will surprise a lot of people using package.el. Imagine this: a user has a bunch of installed packages in .emacs.d/elpa and installs no-littering which consequently moves the elpa directory. The user closes and opens emacs and suddenly init.el is throwing tons of errors and nothing works.

**Comment by tarsius** [comment]
@justbur Yes, completely agree.

@DamienCassou I think the documentation is okay, but am not opposed to improvements.
