### ISSUE TITLE
Better description of the main functionality

### ISSUE THREAD

**Issue by novoid** [tarsius/no-littering#50]
Hi!

I'd consider myself a power-user of Emacs with limited understanding of Elisp and the plumbing inside of Emacs.

I stumbled over your project and it seems interesting since I want to keep a clean Emacs config as well. However, I was not able to determine the main functionality how this goal is achieved with no-littering. I'd suggest to add real-world examples for "without no-littering" and then the view on "with no-littering" differs.

At this moment, I'd be worried what will be modified by no-littering and what won't be affected.

I do think that this can be explained with examples very easily.

Thanks!

**Comment by tarsius** [comment]
The issue this package tries to fix:

> The default paths used to store configuration files and persistent data are not consistent across Emacs packages. [...]

How that is done, aka the "main functionality":

> This package sets out to fix this by changing the values of path variables to put files in either `no-littering-etc-directory` (defaulting to `~/.emacs.d/etc/`) or `no-littering-var-directory` (defaulting to `~/.emacs.d/var/`), [...]

(The current documentation does not mention that configuration files are stored in the `~/.emacs.d/etc` directory and "data files" in the `~/.emacs.d/var` directory. Instead I rely on users seeing the resemblance to `/etc`, the directory used to system configuration files on Unix systems.)

(There is no other functionality beside the "main functionality.)

> At this moment, I'd be worried what will be modified by no-littering

* The values of variables used to configure the location of configuration files and files used by packages to store their data, *which have **already** been themed*.

> and what won't be affected.

* The values of variables used to configure the location of configuration files and of files used by packages to store their data, *which have **not yet** been themed*.
* The values of variables that are **not** used to configure the location of configuration files or of files used by packages to store their data,
* It also does not move any files from the old location to the new location. (This isn't mentioned in the current documentation.)

> I'd suggest to add real-world examples for "without no-littering" and then the view on "with no-littering" differs.

The `tramp` package uses a file to store its "connection history". By default the file is `~/.emacs.d/tramp`. But the location of that file can be changed by changing the value of the variable `tramp-persistency-file-name`. This package (`no-littering`) sets the value of that variable to `~/.emacs.d/var/tramp/persistency.el`. The result of doing that is that `tramp` now stores its connection history in that file, instead of the file that it would use if `no-littering` was not loaded.

**Comment by novoid** [comment]
Hi tarsius,

I have no clue what "default paths", "configuration files" (my .emacs.el?) or "persistent data" is.

I hope that no-littering is *not* touching my own files. The only things within my .emacs.d/ directory that I did not install it are:

- .org-id-locations
- auto-save-list (dir)
- bookmarks
- saved-desktops (dir)
- server (dir)
- url (dir)
- var (dir)

They are moved away? Deleted? Renamed?

All of my "variables" are within ".emacs.d/init.el". Will this file be modified? To what extend?

Thanks for your example. This helped a *lot* to understand the purpose of the package. It be cool to include this (and answers to my questions or false assumptions above) in the README file. It is not about *my* understanding: I guess that many other interested people do pose the same questions I do.

When I understand the consequences, I am happy to give it a try. So far, I am not sure whether or not my ".emacs.d/init.el" will be modified by no-littering which I would not tolerate.

Thanks for your help!

**Comment by tarsius** [comment]
I think the current documentation already answers you questions. Obviously it does fail to do so for you, and I am sorry about that. However I fear that by making things more explicit I would introduce other issues to the documentation, which would make the documentation *worse* for other people. At the very least it would make the documentation longer, which I feel is not warranted by the very limited functionality this package provides. I also fear that by doing that I would confuse other users, which might then ask themselves: "So this does essentially [...], why does he keep going on about it? I thought I understood, but there most be a reason why this is documented to such extends. What did I miss?".

**Comment by novoid** [comment]
I see. I do think I got it. Thanks for your time!
