### ISSUE TITLE
Should we theme epkg-repository?

### ISSUE THREAD

**Issue by DamienCassou** [tarsius/no-littering#51]
I can see in `emacs.g`:

```emacs
(setq epkg-repository (expand-file-name "var/epkgs/" user-emacs-directory))
```

**Comment by tarsius** [comment]
Yes, but only for the benefit of users of both `epkg` and `no-littering` that do not use `borg`.

Regarding `borg`/`emacs.g`: This line is added in one of the very first commits on the `master` branch. That branch does not assimilate `no-littering`. So even after teaching `no-littering` about `epkg`, we would not be able to remove this line from `init.el`. Not without changing the location of `epkg-repository` for users who have not assimilated `no-littering` themselves (or by using a branch in which it is already assimilated).

I have decided that since `borg` installs libraries in `lib` it makes sense that it expects "data" in `var` (like `/etc/` and `/var`). That is why `emacs.g` changes the value of `epkg-repository`. However I don't think `emacs.g` should force `no-littering` onto all `borg` users, so it does not assimilate that in its `master` branch. You can think of `~/.emacs.d/var/epkgs` as a *suggestion* that users might want to put other data next to it.

**Comment by tarsius** [comment]
Done in 1f10dbf40266c8e675e2e10f708f87ec61413ab5.
